import "./globals.css";
import type { Metadata } from "next";
import { Inter, Spectral } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

const spectral = Spectral({
  subsets: ['latin'],
  weight: "400",
  display: 'swap',
  variable: '--font-spectral',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${spectral.variable}`}>
        <ToastContainer />
        {children}
      </body>
    </html>
  );
}
